//! **The MLX estimate-synthesis DECISION BASELINE, emitted by the mechanism itself** (sc-19050,
//! epic 19048 R6).
//!
//! sc-19049 built the candle half of this ([`crate::candle_admission_decisions`]) and left the MLX
//! rows at `resolution: "declared"` — manifest floors and evidence-ladder reachability — because
//! mirroring `mlx_fit_gate`'s estimate synthesis in the Node generator would have forked the very
//! prediction law sc-19050 was about to extract. This module is the other half, built the same way:
//! it drives the REAL functions the request reaches and commits their output, so a later slice goes
//! red on any admission decision it did not enumerate.
//!
//! Regenerate with:
//!
//! ```text
//! SCENEWORKS_REGENERATE_MLX_ADMISSION=1 \
//!   cargo test -p sceneworks-worker mlx_admission_decisions
//! ```
//!
//! # Why this artifact exists, and exactly what it proves
//!
//! sc-19050 is a pure extraction: the two-basis synthesis moved out of `mlx_fit_gate.rs` into
//! [`crate::estimate_synthesis`] with zero admission changes. "Zero" is only a claim unless
//! something re-runs the decision path on both sides of the move.
//!
//! `docs/generated/mlx-estimate-synthesis-decisions.json` was generated by **this exact emitter
//! running against the PRE-extraction gate** (`feature/sc-19048-memory-admission-convergence`, with
//! only this file added). The committed bytes are therefore the old code's output. The test below
//! re-derives them from the POST-extraction module. An empty diff is the proof, and it is not
//! circular: the expectation was produced by code that no longer exists in this tree.
//!
//! # Why the shipped MLX rows still cannot be admission decisions
//!
//! sc-19049's baseline says "sc-19050 upgrades these to evaluated". Verified during this slice:
//! **it cannot, on any lane without real weights on disk.** The synthesis floor is
//! [`crate::estimate_synthesis::floor_weights_bytes`], a pure function of
//! `MemoryProviderContract::asset_facts` — and every weights-free contract builder in the pinned
//! inference bundle injects zeros by contract (gen-core `registry.rs`: *"The fixture must preserve
//! the route declaration and inject zero asset facts without filesystem traversal"*; flux2's own
//! test pins `assert_eq!(contract.asset_facts, Default::default())`). Production fills them from
//! `prepared_file_sizes(spec)`, i.e. real `stat`s. No committed table backfills them either:
//! `capabilities.mlx.json` publishes rung coverage and no byte counts, and the manifest's
//! `diskSizeBytes` is a per-download artifact total, not the conditioning/transformer/decoder split
//! `MemoryAssetFacts` requires.
//!
//! So this artifact does what sc-19049 did with `sequentialCapable`: it **enumerates the input it
//! cannot resolve** rather than inventing one value for it. Every row names the asset-fact vector
//! it was evaluated under ([`INJECTED_ASSET_FACTS`]) and the headroom it was charged
//! ([`INJECTED_HEADROOM_BYTES`]). Everything else — which rungs synthesize a candidate, under which
//! parameters, from which basis, with which decode-quality decision, and what the resulting peak is
//! as a function of those declared inputs — is the shipped contract's own structure driving the
//! real mechanism.
//!
//! What that buys, precisely: the artifact is a complete characterization of the SYNTHESIS
//! MECHANISM over the shipped MLX contract universe. It is **not** a claim about what any shipped
//! route is admitted at on a real machine, and no row should ever be read as one.

use std::collections::BTreeMap;
use std::path::PathBuf;

use gen_core::{MemoryGeometry, MemoryProviderContract, MemoryStrategy};
use sceneworks_core::memory_calibration::Geometry as CalibrationGeometry;
use serde_json::{json, Value};

use crate::estimate_synthesis::{
    binding_phase, evidence_strategy, floor_smallest_parameters, strategy_rung,
    synthesize_estimate_ladder, DecodeQualityRequestDecision, EstimateRequest, MeasuredRungBasis,
    MLX_LANE,
};

/// The committed decisions this module both produces and verifies.
const DECISIONS: &str =
    include_str!("../../../docs/generated/mlx-estimate-synthesis-decisions.json");

const DECISIONS_RELATIVE_PATH: &str = "docs/generated/mlx-estimate-synthesis-decisions.json";
const REGENERATE_ENV: &str = "SCENEWORKS_REGENERATE_MLX_ADMISSION";

/// **The enumerated asset-fact vector.** Not a measurement and never presented as one — see the
/// module header. Chosen so every branch of
/// [`crate::estimate_synthesis::floor_weights_bytes`] lands on a DISTINCT number, which is what
/// makes a mutation of that function visible in this artifact:
///
/// * `heavy = base - conditioning = 8 GB`
/// * `BoundedTransformerResidency` engaged ⇒ `heavy - transformer = 2 GB`
/// * `StagedResidency` engaged ⇒ `max(conditioning, heavy)`; otherwise `conditioning + heavy`
///
/// so the four reachable combinations are 12, 8, 6 and 4 GB respectively — no two alias.
const INJECTED_ASSET_FACTS: (u64, u64, u64, u64, u64) = (
    12_000_000_000, // base
    4_000_000_000,  // conditioning
    6_000_000_000,  // transformer
    2_000_000_000,  // decoder
    0,              // overlay
);

/// **The enumerated headroom.** MLX's own headroom law (`MlxRequestPlan::generic_headroom_bytes`)
/// is a backend-supplied PARAMETER of the mechanism and was not moved by this extraction, so it is
/// held at one declared value here rather than re-implemented. Non-round on purpose: a floor row
/// that accidentally dropped the headroom term would be obvious.
const INJECTED_HEADROOM_BYTES: u64 = 3_210_000_000;

/// The request cells. Two geometries exercise the extrapolation scale on both sides of the basis
/// (below-basis clamps to 1.0, above-basis scales), and `use_pid` toggles the PiD decode-route
/// branch of the parameter law without doubling the whole grid.
const CELLS: &[(u32, u32, bool)] = &[
    (1024, 1024, false),
    (2048, 2048, false),
    (1024, 1024, true),
    // OFF-GRID on purpose. A provider with a declared decode-quality scope publishes no
    // production-latent row here, which is the only way to reach the `candidates.is_empty()` arm of
    // `floor_parameter_candidates` — and therefore the only way the guard that stops BoundedDecode
    // itself from surviving without an admitted (edge, overlap) pair is exercised at all.
    (1023, 1025, false),
];

/// The measured cell every fitted basis is anchored at. Below both request geometries, so the
/// scale is > 1 in both cells and the clamp is exercised by the 768-basis/1024-request pair only
/// through its own ratio.
const BASIS_GEOMETRY: CalibrationGeometry = CalibrationGeometry {
    width: 768,
    height: 768,
    batch: 1,
    frames: 1,
};

/// `(conditioning, denoise, decode, envelope)` peaks of one measured basis: the canonical phase
/// order plus the admission envelope the fitted arm scales.
type BasisTriple = (u64, u64, u64, u64);

/// One named basis set — a label and the triple it stamps on every rung's basis, `None` meaning no
/// measured cell at all.
type BasisSet = (&'static str, Option<BasisTriple>);

/// The basis sets, each a declared per-phase triple at [`BASIS_GEOMETRY`].
///
/// * `none` — no measured cell; every rung takes the weights+headroom floor.
/// * `stable` — denoise binds at the basis and still binds after any scale ≥ 1, so the
///   binding-phase constraint passes and the fitted arm is emitted.
/// * `flipping` — conditioning binds at the basis (10 > 4, 2). At 1024² the scale is 1.78 and
///   conditioning still binds (fitted emitted); at 2048² the scale is 7.11, denoise reaches 28.4
///   and the binding phase FLIPS, so `ESTIMATE_ADMISSION_REQUIRES_MEASURED_BINDING_PHASE` refuses
///   the fitted candidate and the rung falls back to the floor. One corpus, both sides of the
///   constraint.
/// * `stable_foreign_identity` — `stable`'s numbers under a DRIFTED calibration fingerprint.
const BASIS_SETS: &[BasisSet] = &[
    ("none", None),
    (
        "stable",
        // (conditioning, denoise, decode, envelope)
        Some((1_000_000_000, 4_000_000_000, 2_000_000_000, 5_000_000_000)),
    ),
    (
        "flipping",
        Some((10_000_000_000, 4_000_000_000, 2_000_000_000, 11_000_000_000)),
    ),
    // Identical numbers to `stable`, but the basis is stamped with a FOREIGN calibration
    // fingerprint (see `bases_for`). Every fitted candidate must disappear: a provider whose
    // estimator drifted from the packaged records must not receive fitted candidates built from
    // them, and on a legacy route that identity gate is the ONLY thing enforcing it.
    (
        "stable_foreign_identity",
        Some((1_000_000_000, 4_000_000_000, 2_000_000_000, 5_000_000_000)),
    ),
];

/// The basis set whose calibration fingerprint is deliberately not the loaded contract's.
const FOREIGN_IDENTITY_BASIS_SET: &str = "stable_foreign_identity";

fn injected_contract(surface_contract: &MemoryProviderContract) -> MemoryProviderContract {
    let mut contract = surface_contract.clone();
    let (base, conditioning, transformer, decoder, overlay) = INJECTED_ASSET_FACTS;
    contract.asset_facts.base_bytes = base;
    contract.asset_facts.conditioning_bytes = conditioning;
    contract.asset_facts.transformer_bytes = transformer;
    contract.asset_facts.decoder_bytes = decoder;
    contract.asset_facts.overlay_bytes = overlay;
    contract
}

/// Build one basis per implemented rung, keyed to the contract's OWN engaged composition and
/// calibration identity so the fitted arm's identity gate can actually pass.
///
/// The basis parameters come from [`floor_smallest_parameters`] — the mechanism is being used to
/// construct an INPUT here, not to derive an expected output. A measured cell's parameters are
/// exactly "the knobs the engaged composition required", which is what that function answers; with
/// `Default::default()` instead, `validate_selection` would reject every fitted candidate and the
/// fitted arm would never be exercised at all. [`tests::the_corpus_exercises_every_arm`] is the
/// guard that this construction keeps the arm live.
fn bases_for(
    contract: &MemoryProviderContract,
    triple: Option<BasisTriple>,
    foreign_identity: bool,
) -> Vec<MeasuredRungBasis> {
    let Some((conditioning, denoise, decode, envelope)) = triple else {
        return Vec::new();
    };
    let Some(identity) = contract.calibration.as_ref() else {
        // A contract with no calibration identity gets no fitted candidates at all — fail closed.
        // Emitting bases it can never match would only pad the artifact.
        return Vec::new();
    };
    let mut bases = Vec::new();
    for strategy in MemoryStrategy::ALL {
        let engaged = contract.engaged_composition(strategy);
        let Some(parameters) = floor_smallest_parameters(contract, &engaged) else {
            continue;
        };
        bases.push(MeasuredRungBasis {
            rung: strategy_rung(strategy),
            parameters,
            engaged_composition: engaged,
            load_shape: contract.load_shape,
            calibration_abi: identity.abi,
            calibration_fingerprint: if foreign_identity {
                format!("{}-drifted", identity.fingerprint)
            } else {
                identity.fingerprint.clone()
            },
            geometry: BASIS_GEOMETRY,
            conditioning_peak_bytes: conditioning,
            denoise_peak_bytes: denoise,
            decode_peak_bytes: decode,
            envelope_peak_bytes: envelope,
            record_id: format!("synthetic-basis-{:?}", strategy_rung(strategy)),
        });
    }
    bases
}

fn decode_quality_label(decision: &DecodeQualityRequestDecision) -> Value {
    match decision {
        DecodeQualityRequestDecision::NotDeclared => json!({ "kind": "not_declared" }),
        DecodeQualityRequestDecision::NotEngaged { strategy } => {
            json!({ "kind": "not_engaged", "strategy": format!("{strategy:?}") })
        }
        DecodeQualityRequestDecision::Admitted {
            strategy,
            tile_edge,
            overlap,
            evidence_sha256,
        } => json!({
            "kind": "admitted",
            "strategy": format!("{strategy:?}"),
            "tileEdge": tile_edge,
            "overlap": overlap,
            "evidenceSha256": evidence_sha256,
        }),
        DecodeQualityRequestDecision::Refused {
            strategy,
            tile_edge,
            overlap,
            evidence_sha256,
            reason,
        } => json!({
            "kind": "refused",
            "strategy": format!("{strategy:?}"),
            "tileEdge": tile_edge,
            "overlap": overlap,
            "evidenceSha256": evidence_sha256,
            "reason": reason,
        }),
        DecodeQualityRequestDecision::Unmeasured { strategy, reason } => json!({
            "kind": "unmeasured",
            "strategy": format!("{strategy:?}"),
            "reason": reason,
        }),
    }
}

fn parameters_json(parameters: gen_core::MemoryStrategyParameters) -> Value {
    json!({
        "decodeTileEdge": parameters.decode_tile_edge,
        "decodeOverlap": parameters.decode_overlap,
        "attentionChunkSize": parameters.attention_chunk_size,
        "transformerWindowSize": parameters.transformer_window_size,
        "transformerWindowComponent": parameters
            .transformer_window_component
            .map(|component| format!("{component:?}")),
    })
}

/// Drive the real mechanism over the shipped MLX contract universe.
fn build_decisions() -> Value {
    let registry = crate::inference_runtime::memory_contract_surface_registry()
        .expect("the linked MLX bundle publishes weights-free memory-contract surfaces");
    let surfaces = registry
        .memory_contract_surfaces()
        .expect("every MLX memory registration has its paired weights-free surface");

    // Deterministic order, independent of registration order.
    let mut ordered: BTreeMap<(String, String, String, String), Value> = BTreeMap::new();
    // Distinct ladders, keyed by their own canonical serialization so the table's order is a
    // property of the CONTENT and never of registration order.
    let mut ladders: BTreeMap<String, Value> = BTreeMap::new();
    let mut rows = Vec::new();
    let mut surface_count = 0_usize;

    let mut sorted: Vec<_> = surfaces
        .into_iter()
        .filter(|surface| surface.contract.backend.backend_id() == "mlx")
        .collect();
    sorted.sort_by(|left, right| {
        (
            &left.contract.provider_id,
            format!("{:?}", left.selector.tier),
            format!("{:?}", left.selector.offload_policy),
            format!("{:?}", left.selector.load_shape),
        )
            .cmp(&(
                &right.contract.provider_id,
                format!("{:?}", right.selector.tier),
                format!("{:?}", right.selector.offload_policy),
                format!("{:?}", right.selector.load_shape),
            ))
    });

    for surface in &sorted {
        surface_count += 1;
        let provider = surface.contract.provider_id.clone();
        let tier_key = format!("{:?}", surface.selector.tier);
        let offload = format!("{:?}", surface.selector.offload_policy);
        let load_shape = format!("{:?}", surface.selector.load_shape);
        ordered.insert(
            (
                provider.clone(),
                tier_key.clone(),
                offload.clone(),
                load_shape.clone(),
            ),
            Value::Null,
        );
        let contract = injected_contract(&surface.contract);
        let tier = crate::mlx_fit_gate::spec_numeric_tier(&provider, &surface.spec);

        for (basis_label, triple) in BASIS_SETS {
            let bases = bases_for(
                &contract,
                *triple,
                *basis_label == FOREIGN_IDENTITY_BASIS_SET,
            );
            for (width, height, use_pid) in CELLS {
                let geometry = MemoryGeometry {
                    width: *width,
                    height: *height,
                    batch: 1,
                    frames: 1,
                    reference_count: 0,
                };
                // ── THE REAL MECHANISM. Everything below is `estimate_synthesis`' own code. ──
                let ladder = synthesize_estimate_ladder(
                    &EstimateRequest {
                        lane: MLX_LANE,
                        contract: &contract,
                        tier,
                        mode_key: "text_to_image",
                        overlay: None,
                        geometry,
                        use_pid: *use_pid,
                        calibration_fingerprint: contract
                            .calibration
                            .as_ref()
                            .map(|identity| identity.fingerprint.as_str()),
                        headroom_bytes: INJECTED_HEADROOM_BYTES,
                    },
                    &bases,
                );

                let candidates: Vec<Value> = ladder
                    .estimates
                    .iter()
                    .map(|estimate| {
                        json!({
                            "strategy": format!("{:?}", estimate.selection.strategy),
                            "basis": estimate.basis.as_key(),
                            "predictedPeakBytes": estimate.evidence.predicted_peak_bytes,
                            "parameters": parameters_json(estimate.selection.parameters),
                            "engagedComposition": estimate
                                .evidence
                                .key
                                .engaged_composition
                                .iter()
                                .map(|strategy| format!("{strategy:?}"))
                                .collect::<Vec<_>>(),
                            "decodeQuality": decode_quality_label(&estimate.decode_quality),
                        })
                    })
                    .collect();
                let decisions: Vec<Value> = ladder
                    .decode_quality_decisions
                    .iter()
                    .map(decode_quality_label)
                    .collect();

                // Deduplicated: 561 shipped surfaces collapse to a small number of distinct
                // ladders, because a provider's contract structure is frequently identical across
                // its offload-policy and load-shape surfaces. Emitting the ladder ONCE and
                // referencing it keeps every coordinate's decision recorded — no row is dropped —
                // while making a mechanism change show up as a diff in a table a human can read
                // rather than as ten thousand identical edits.
                let ladder_payload = json!({
                    "candidates": candidates,
                    "decodeQualityDecisions": decisions,
                });
                let ladder_key =
                    serde_json::to_string(&ladder_payload).expect("a ladder payload serializes");
                ladders.insert(ladder_key.clone(), ladder_payload);
                rows.push(json!({
                    "provider": provider,
                    "surfaceTier": tier_key,
                    "surfaceOffloadPolicy": offload,
                    "surfaceLoadShape": load_shape,
                    "basisSet": basis_label,
                    "width": width,
                    "height": height,
                    "usePid": use_pid,
                    "ladderKey": ladder_key,
                }));
            }
        }
    }

    // Canonical ids assigned in content order, then substituted into every row.
    let ladder_ids: BTreeMap<&String, usize> = ladders
        .keys()
        .enumerate()
        .map(|(index, key)| (key, index))
        .collect();
    let ladder_table: Vec<Value> = ladders
        .iter()
        .enumerate()
        .map(|(index, (_, payload))| {
            let mut entry = payload.clone();
            entry["ladderId"] = json!(index);
            entry
        })
        .collect();
    for row in &mut rows {
        let key = row["ladderKey"]
            .as_str()
            .expect("row ladder key")
            .to_owned();
        let id = *ladder_ids
            .get(&key)
            .expect("every row's ladder is in the table");
        row.as_object_mut().expect("row object").remove("ladderKey");
        row["ladderId"] = json!(id);
    }

    let (base, conditioning, transformer, decoder, overlay) = INJECTED_ASSET_FACTS;
    json!({
        "schemaVersion": 1,
        "story": "sc-19050",
        "generatedBy": format!(
            "{REGENERATE_ENV}=1 cargo test -p sceneworks-worker mlx_admission_decisions"
        ),
        "producedBy": {
            "module": "crates/sceneworks-worker/src/mlx_admission_decisions.rs",
            "mechanismModule": "crates/sceneworks-worker/src/estimate_synthesis.rs",
            "entryPoints": [
                "estimate_synthesis::synthesize_estimate_ladder",
                "estimate_synthesis::floor_parameter_candidates",
                "estimate_synthesis::floor_weights_bytes",
                "estimate_synthesis::floor_smallest_parameters",
                "estimate_synthesis::estimate_evidence",
                "estimate_synthesis::binding_phase",
                "estimate_synthesis::extrapolation_scale",
            ],
            "contractUniverse":
                "crate::inference_runtime::memory_contract_surface_registry() — the LINKED MLX \
                 bundle's weights-free memory-contract surfaces",
        },
        "enumeratedInputs": {
            "why":
                "The synthesis floor is a pure function of MemoryProviderContract::asset_facts, and \
                 every weights-free contract builder in the pinned inference bundle injects zeros by \
                 contract. No CPU lane can resolve real asset facts and no committed table backfills \
                 them, so they are ENUMERATED here — the same posture sc-19049 took for \
                 sequentialCapable — rather than invented. These rows characterize the mechanism over \
                 the shipped contract structures; they are NOT admission decisions for any shipped \
                 route on a real machine.",
            "assetFacts": {
                "baseBytes": base,
                "conditioningBytes": conditioning,
                "transformerBytes": transformer,
                "decoderBytes": decoder,
                "overlayBytes": overlay,
            },
            "headroomBytes": INJECTED_HEADROOM_BYTES,
            "headroomIsABackendParameter":
                "MlxRequestPlan::generic_headroom_bytes — supplied by the MLX lane, untouched by \
                 the sc-19050 extraction, therefore held at one declared value here",
        },
        "corpus": {
            "cells": CELLS
                .iter()
                .map(|(width, height, use_pid)| json!({
                    "width": width, "height": height, "usePid": use_pid
                }))
                .collect::<Vec<_>>(),
            "basisGeometry": {
                "width": BASIS_GEOMETRY.width,
                "height": BASIS_GEOMETRY.height,
                "batch": BASIS_GEOMETRY.batch,
                "frames": BASIS_GEOMETRY.frames,
            },
            "basisSets": BASIS_SETS
                .iter()
                .map(|(label, triple)| match triple {
                    Some((conditioning, denoise, decode, envelope)) => json!({
                        "label": label,
                        "conditioningPeakBytes": conditioning,
                        "denoisePeakBytes": denoise,
                        "decodePeakBytes": decode,
                        "envelopePeakBytes": envelope,
                    }),
                    None => json!({ "label": label }),
                })
                .collect::<Vec<_>>(),
        },
        "summary": {
            "surfaces": surface_count,
            "distinctSurfaceSelectors": ordered.len(),
            "rows": rows.len(),
            "distinctLadders": ladder_table.len(),
        },
        "ladders": ladder_table,
        "rows": rows,
    })
}

fn rendered_decisions() -> String {
    format!(
        "{}\n",
        serde_json::to_string_pretty(&build_decisions()).expect("decisions serialize")
    )
}

fn decisions_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(DECISIONS_RELATIVE_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **The empty-diff proof.** Under `SCENEWORKS_REGENERATE_MLX_ADMISSION=1` this WRITES the
    /// artifact; otherwise it fails on any drift between the committed file and what the mechanism
    /// produces right now.
    ///
    /// The committed bytes were produced by this emitter running against the PRE-extraction gate.
    /// Passing here therefore means the extraction changed no decision — proven by re-running the
    /// path, not by re-deriving an expectation from the code under test.
    #[test]
    fn committed_decisions_match_the_mechanism() {
        let rendered = rendered_decisions();
        if std::env::var(REGENERATE_ENV).is_ok_and(|value| value == "1") {
            // Rendered successfully before any write — never truncate the checked-in artifact with
            // a partial or failed generation.
            std::fs::write(decisions_path(), &rendered).expect("write the decisions artifact");
            return;
        }
        assert_eq!(
            DECISIONS.replace("\r\n", "\n"),
            rendered,
            "{DECISIONS_RELATIVE_PATH} no longer matches what the estimate-synthesis mechanism \
             produces. For sc-19050 that is a FAILED extraction: the slice's whole contract is that \
             admission decisions do not move. For a later slice that deliberately changes the law, \
             enumerate and justify the decision change, then regenerate with \
             `{REGENERATE_ENV}=1 cargo test -p sceneworks-worker mlx_admission_decisions`."
        );
    }

    /// **Anti-vacuity.** A baseline that never reaches an arm cannot detect a change to it. Both
    /// bases, the binding-phase refusal, and the decode-quality decision surface must all be
    /// exercised by the committed corpus.
    #[test]
    fn the_corpus_exercises_every_arm() {
        let decisions = build_decisions();
        let rows = decisions["rows"].as_array().expect("rows");
        assert!(
            !rows.is_empty(),
            "the linked MLX bundle produced no surfaces"
        );

        let ladders = decisions["ladders"].as_array().expect("ladders");
        let mut fitted = 0_usize;
        let mut floor = 0_usize;
        let mut decode_quality_kinds = std::collections::BTreeSet::new();
        for row in ladders {
            for candidate in row["candidates"].as_array().expect("candidates") {
                match candidate["basis"].as_str() {
                    Some("fitted_curve") => fitted += 1,
                    Some("floor") => floor += 1,
                    other => panic!("unexpected candidate basis {other:?}"),
                }
                decode_quality_kinds.insert(
                    candidate["decodeQuality"]["kind"]
                        .as_str()
                        .expect("decode-quality kind")
                        .to_owned(),
                );
            }
        }
        assert!(fitted > 0, "no fitted-basis candidate in the whole corpus");
        assert!(
            floor > 0,
            "no weights+headroom floor candidate in the whole corpus"
        );
        assert!(
            decode_quality_kinds.len() > 1,
            "the decode-quality decision surface collapsed to {decode_quality_kinds:?}"
        );

        // The binding-phase constraint must actually fire somewhere: the `flipping` basis set at
        // 2048² is constructed to trip it, so that cell must carry strictly fewer fitted candidates
        // than the same set at 1024².
        let fitted_in = |basis_set: &str, width: u64| -> usize {
            rows.iter()
                .filter(|row| row["basisSet"] == basis_set && row["width"].as_u64() == Some(width))
                .map(|row| {
                    let id = row["ladderId"].as_u64().expect("ladderId") as usize;
                    ladders[id]["candidates"]
                        .as_array()
                        .expect("candidates")
                        .iter()
                        .filter(|candidate| candidate["basis"] == "fitted_curve")
                        .count()
                })
                .sum()
        };
        // The calibration-identity gate must actually bite: the foreign-identity set carries the
        // same numbers as `stable`, so any fitted candidate it produces is one the gate failed to
        // refuse.
        assert!(
            fitted_in("stable", 1024) > 0,
            "the stable basis set produced no fitted candidate, so the foreign-identity comparison \
             below would be vacuous"
        );
        assert_eq!(
            fitted_in(FOREIGN_IDENTITY_BASIS_SET, 1024),
            0,
            "a basis measured under a DRIFTED calibration identity seeded a fitted estimate"
        );
        assert!(
            fitted_in("flipping", 2048) < fitted_in("flipping", 1024),
            "ESTIMATE_ADMISSION_REQUIRES_MEASURED_BINDING_PHASE never fired: the flipping basis \
             set yielded {} fitted candidates at 2048² and {} at 1024²",
            fitted_in("flipping", 2048),
            fitted_in("flipping", 1024),
        );
    }

    /// The enumerated inputs must be stated in the artifact, and no row may publish a resolved
    /// asset-fact column — that would be the fabricated column this baseline exists to prevent.
    #[test]
    fn the_unresolvable_input_is_enumerated_not_invented() {
        let decisions = build_decisions();
        assert_eq!(
            decisions["enumeratedInputs"]["headroomBytes"].as_u64(),
            Some(INJECTED_HEADROOM_BYTES)
        );
        assert!(decisions["enumeratedInputs"]["why"]
            .as_str()
            .is_some_and(|why| why.contains("NOT admission decisions")));
        for row in decisions["rows"].as_array().expect("rows") {
            assert!(
                row.get("assetFactsBytes").is_none() && row.get("measuredPeakBytes").is_none(),
                "{}: a row must not publish a resolved measurement column",
                row["provider"]
            );
        }
    }

    /// The rung mapping the emitter uses to build bases is the mechanism's own, in both
    /// directions — so a basis can never be labelled with a rung the synthesis would not match.
    #[test]
    fn emitted_bases_use_the_mechanisms_own_rung_mapping() {
        for strategy in MemoryStrategy::ALL {
            assert_eq!(evidence_strategy(strategy_rung(strategy)), strategy);
        }
        assert_eq!(
            binding_phase(
                BASIS_SETS[2].1.expect("flipping triple").0,
                BASIS_SETS[2].1.expect("flipping triple").1,
                BASIS_SETS[2].1.expect("flipping triple").2,
            ),
            crate::estimate_synthesis::BindingPhase::Conditioning,
            "the flipping basis set must BIND on conditioning at the basis geometry, or it cannot \
             flip when the scale grows"
        );
    }
}
