// Live denoise preview discoverability (sc-16965, epic 16948).
//
// Before this, `WorkerProgressCard` rendered three different situations identically — the model
// genuinely cannot preview; the model can and the first frame has not arrived yet (model load, text
// encode, the whole pre-denoise phase, tens of seconds on a cold cache); previews are broken for
// that route. A user watching the second had no way to know whether to keep waiting.
//
// CAPABILITY-DRIVEN — never a hardcoded id list. Everything here reads `preview.byBackend` off the
// model catalog entry, exactly as `modelEligibility.js` reads `audio.supportsStreaming`. The catalog
// gets that field from `config/manifests/builtin.preview-support.jsonc`, generated by
// `npm run gen:preview-support` and guarded by `data/previewSupportCatalog.test.js` on every PR.

import { terminalStatuses } from "./jobTypes.js";

/**
 * Stages a job passes through BEFORE its first denoise step.
 *
 * The worker reports `loading_model` while the text encoder and render components load, and flips to
 * `generating` on the first denoise step. So "still in one of these stages" is exactly "denoise has
 * not reported yet".
 */
export const PRE_DENOISE_STAGES = new Set([
  "queued",
  "pending_caption",
  "preparing",
  "downloading",
  "importing",
  "loading_model",
  "estimating",
]);

/**
 * The 1-based denoise step a running job last reported, or `null` if it has not reported one.
 *
 * ## Why the placeholder needs this
 *
 * The first `generating` update does NOT carry frame 1. Traced end to end at inference pin
 * `d4802320`:
 *
 * 1. `candle-gen/src/sampler.rs` `run_curated_sampler` calls `on_progress(Progress::Step { … })`
 *    and only THEN `hook.emit(…)` for the preview, inside the same evaluation closure.
 * 2. `image_jobs/stream.rs` sends both down ONE mpsc channel (`send_gen_progress` /
 *    `preview_sink_for`), so the worker sees them in that order.
 * 3. `image_jobs/base.rs` POSTs in the `GenEvent::Step` arm; the `GenEvent::Preview` arm
 *    deliberately does NOT post — the frame "rides the NEXT Step/Decoding update", by design, so
 *    previews add zero requests to the existing cadence.
 *
 * So the POST that first reports `generating` is emitted *before* frame 1 exists, and the frame
 * lands on the step-2 POST. Bounding the placeholder on the pre-denoise stage set alone therefore
 * produced a one-step blink of the very cell this story adds: `pending` (placeholder) →
 * `supported` (cell removed) → `live` (cell restored). Holding `pending` across step 1 closes it.
 *
 * There is no structured step field on the job record — `ProgressRequest` carries the count only
 * inside the human-facing `message` ("Image 1/2 — step 3/20.", built in `base.rs`) — so this reads
 * it from there. A message that does not match yields `null`, which degrades to the old behaviour
 * (the blink) rather than to a stuck placeholder: the failure direction is the safe one.
 */
const DENOISE_STEP_MESSAGE = /\bstep\s+(\d+)\s*\/\s*(\d+)/i;

export function reportedDenoiseStep(job) {
  const match = DENOISE_STEP_MESSAGE.exec(typeof job?.message === "string" ? job.message : "");
  if (!match) return null;
  const current = Number.parseInt(match[1], 10);
  return Number.isFinite(current) ? current : null;
}

/**
 * Whether `job` is still inside the window where a supporting route cannot have delivered a frame
 * yet: any pre-denoise stage, or the FIRST denoise step (see {@link reportedDenoiseStep}).
 *
 * Bounded at one step. A route that advertises support but never emits shows the placeholder for
 * its first step and then degrades to exactly today's card — no timers, no thresholds, no stuck
 * placeholder for the whole render.
 */
function awaitingFirstFrame(job) {
  if (PRE_DENOISE_STAGES.has(job?.stage ?? job?.status)) return true;
  const step = reportedDenoiseStep(job);
  return step !== null && step <= 1;
}

/**
 * Which tensor backend the worker running `job` uses — the KEY the preview flag is stored under.
 *
 * `supports_preview` is a property of the engine, not the model: `krea_2_turbo` is true on MLX and
 * was false on candle for most of epic 16948, and SenseNova stays candle-only permanently. So the
 * answer depends on which worker picked the job up.
 *
 * The off-Mac candle worker advertises the `"candle"` lane marker capability (`gpu.rs`
 * `with_candle_capabilities`) — the same marker the API's routing gate keys off. The macOS MLX
 * worker registers under the fixed gpu id `"mlx"`, and its image jobs stamp `backend: "mlx"` on
 * every progress update (`backend_label`). Anything else (a CPU utility worker, a snapshot with no
 * worker resolved yet) is `null` — unknown, which renders as it did before this story.
 */
export function previewBackendForWorker(worker, job) {
  const capabilities = Array.isArray(worker?.capabilities) ? worker.capabilities : [];
  if (capabilities.includes("candle")) return "candle";
  if (worker?.gpuId === "mlx" || job?.backend === "mlx") return "mlx";
  return null;
}

/**
 * Whether `model` advertises live preview on `backend`: `true`, `false`, or `null` for UNKNOWN.
 *
 * `null` is a first-class answer and must never be folded into `false`. It means the catalog has no
 * opinion — the model is not engine-backed, that backend never registered its engine, or that
 * backend's facts file has not been dumped on this build. Claiming "no live preview" there would be
 * asserting something we did not measure.
 */
export function modelPreviewSupport(model, backend) {
  if (!backend) return null;
  const byBackend = model?.preview?.byBackend;
  if (!byBackend || typeof byBackend !== "object") return null;
  const supported = byBackend[backend];
  return typeof supported === "boolean" ? supported : null;
}

/** Look a job's generation model up in the catalog. */
export function modelForJob(job, models) {
  const id = job?.payload?.model;
  if (!id || !Array.isArray(models)) return null;
  return models.find((model) => model?.id === id) ?? null;
}

/**
 * Job types that run the denoise lane and can therefore stream `PreviewSink` frames
 * (`run_image_generate_job` dispatches both by payload model + mode).
 *
 * A job-TYPE gate, not a model-id allowlist: `model_download` and `lora_train` payloads also carry a
 * `model` field, so without this a download of `krea_2_turbo` would sit in `downloading` — a
 * pre-denoise stage — and grow a "preview starting…" cell for a job that will never denoise
 * anything. `image_upscale` / `image_detail` are excluded for the same reason: they are engine work,
 * but not the sampler loop the preview sink hangs off.
 */
export const PREVIEW_JOB_TYPES = new Set(["image_generate", "image_edit"]);

/**
 * The card's live-preview state for one job. Total — every job gets exactly one of:
 *
 * - `"live"`        a streamed frame is on the record and the job is still running.
 * - `"pending"`     the route supports preview, the job is running, and no frame CAN have arrived
 *                   yet — pre-denoise, or the first denoise step, whose POST is emitted before
 *                   frame 1 exists. THE state this story exists to make visible: show the
 *                   placeholder.
 * - `"supported"`   the route supports preview but we are neither showing a frame nor inside that
 *                   window (terminal, or past step 1 with nothing emitted).
 * - `"unsupported"` the route is wired and does NOT preview. Render exactly as before — no
 *                   placeholder, no explanatory chrome; a permanent "no live preview" label on
 *                   every non-previewing model would be noise on the majority of renders.
 * - `"unknown"`     no answer. Also renders exactly as before.
 *
 * Terminal jobs never reach `"pending"` or `"live"`, matching the `terminalStatuses` guard on
 * `livePreviewInterimAssets` — a stale frame left in the record by a failure between POSTs must not
 * resurface, and a finished job is not waiting for anything.
 */
export function livePreviewState(job, model, backend) {
  const terminal = terminalStatuses.has(job?.status);
  const hasFrame = !!job?.result?.previewFrame?.dataUrl;
  if (hasFrame && !terminal) return "live";

  if (!PREVIEW_JOB_TYPES.has(job?.type)) return "unknown";
  const supported = modelPreviewSupport(model, backend);
  if (supported === null) return "unknown";
  if (supported === false) return "unsupported";
  if (!terminal && awaitingFirstFrame(job)) return "pending";
  return "supported";
}

/** The interim-thumbnail id of the "waiting for the first frame" placeholder cell. */
export const PREVIEW_PLACEHOLDER_ID = "live-denoise-preview-pending";

/**
 * The placeholder cell shown while a supporting job is still pre-denoise, shaped as an interim
 * thumbnail so it occupies the SAME grid slot the real frame will take — the cell does not jump
 * when the first frame lands, it just fills in.
 *
 * `[]` for every other state, which is what keeps a non-supporting model rendering exactly as it
 * did before this story.
 */
export function livePreviewPlaceholderAssets(previewState) {
  if (previewState !== "pending") return [];
  return [
    {
      id: PREVIEW_PLACEHOLDER_ID,
      type: "image",
      __interim: true,
      __previewPlaceholder: true,
    },
  ];
}
