import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile as fsWrite } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { buildReceipt, cancellationSafe, compareReceipts, detectFullCacheTemporary, readDarwinMemory, readSealedJson, sha256, validateCampaign, validateReceipt, writeSealedJson } from "./kv-baseline-harness.mjs";

const life = Object.fromEntries(["append","chunkedPrefill","singleShotPrefill","promptCacheReuse","trim","rollback","clear","cancel","clone","batchSplit","batchMerge","prefixCopyOnWrite","pageImport","pageExport","serialization","restore","denseFallback","postRunRelease"].map(k=>[k,true]));
const fixture = (mode="dense", extra={}) => buildReceipt({
  runId: mode, capturedAt:"2026-08-29T12:00:00Z", mode, status:"complete",
  provenance:{sceneWorksRevision:"a".repeat(40),inferenceRevision:"b".repeat(40),mlxRevision:"c".repeat(40),os:"macOS",xcode:"Xcode",hardware:"Apple",modelId:"fixture",modelFileSha256:"d".repeat(64),powerMode:"AC",thermalState:"nominal",command:"fixture"},
  matrix:{family:"llama",contextBand:"short",requestMode:"single",prefillMode:"single-shot",processTemperature:"cold"},
  geometry:{batch:1,queryHeads:8,kvHeads:8,headDimension:128,queryLength:1,kvLength:4096,layers:2,elementBytes:2,capacity:4096},
  memory:{modelWeightsBytes:1000,persistentKvBytes:mode==="dense"?1000:500,transientWorkspaceBytes:100,denseTheoreticalKvBytes:33554432,
    phaseSamples:["process-start","weights-loaded","prefill-peak","first-token","decode-steady","prompt-cache-reuse","cancellation-cleanup","post-run-release"].map((phase,i)=>({phase,pid:9,source:"footprint -p",timestamp:`2026-08-29T12:00:0${i}.000Z`,physFootprintBytes:i===0?2000:(i===7?2000:(mode==="dense"?4000:3000)),mlx:{source:"mlx_rs::memory",activeBytes:100,cacheBytes:10,peakBytes:110}})),
    allocationEvents:[{kind:"compressed_cache",role:"cache",lifetime:"persistent",phase:"decode-steady",timestamp:"2026-08-29T12:00:04.000Z",bytes:500}],reconciliation:{expectedDenseKvBytes:33554432,observedPersistentKvBytes:mode==="dense"?1000:500,toleranceBytes:0},release:{verified:true,afterBytes:2000}},
  timings:{loadMs:1,prefillMs:2,ttftMs:2.5,firstTokenMs:3,decodeTokensPerSecond:mode==="dense"?100:98,coldCompileMs:4,warmCompileMs:1,samples:[1,2,3,4,5],summary:{mean:3,p95:5,variance:1}},
  quality:{parityMaxError:0,perplexityDelta:0,greedyTokenAgreement:1,structuredToolAgreement:1,needleRetrieval:1,multiTurnPromptCache:1,statistics:{repeats:5,warmups:2,confidenceInterval:"95% bootstrap",outlierPolicy:"report all samples; no silent deletion",variancePolicy:"dense baseline variance band is frozen before POC results"}},
  lifecycle:life,cancellation:{cleanupVerified:true},...extra
});
test("sealed comparison and canonical hash",()=>{const d=fixture(),c=fixture("compressed");assert.doesNotThrow(()=>validateReceipt(d));assert.equal(compareReceipts(d,c).persistentKvReduction,.5);d.memory.persistentKvBytes=2;assert.throws(()=>validateReceipt(d),/receiptSha256 mismatch/);});
test("real footprint units and identity",()=>{assert.deepEqual(readDarwinMemory(9,()=>"phys_footprint: 1664 KB","prefill","t"),{phase:"prefill",pid:9,source:"footprint -p",timestamp:"t",physFootprintBytes:1703936});assert.throws(()=>readDarwinMemory(9,()=>"phys_footprint: 2 bananas"),/units/);});
test("attribution detection and lifecycle cleanup",async()=>{assert.equal(detectFullCacheTemporary([{kind:"dense_cache_temporary",role:"cache",lifetime:"transient",phase:"decode",timestamp:"t",bytes:100}],100).detected,true);assert.equal(detectFullCacheTemporary([{kind:"dense_cache",role:"cache",lifetime:"persistent",phase:"decode",timestamp:"t",bytes:100}],100).detected,false);let n=0;await assert.rejects(cancellationSafe(async()=>{throw Error("cancel")},async()=>{n++}));const ac=new AbortController();ac.abort();await assert.rejects(cancellationSafe(async()=>{},async()=>{n++},ac.signal));assert.equal(n,2);});
test("sidecar verification and incomplete campaign",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"kv-seal-")),file=path.join(dir,"receipt.json");await writeSealedJson(file,fixture());assert.equal((await readSealedJson(file)).runId,"dense");await fsWrite(file+".sha256","0".repeat(64));await assert.rejects(readSealedJson(file),/sidecar hash mismatch/);await rm(dir,{recursive:true,force:true});assert.throws(()=>validateCampaign([fixture()]),/campaign incomplete/);});
test("sidecar covers exact bytes and CLI compare preserves compressed input",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"kv-cli-")),dense=path.join(dir,"dense.json"),compressed=path.join(dir,"compressed.json"),out=path.join(dir,"comparison.json");await writeSealedJson(dense,fixture());await writeSealedJson(compressed,fixture("compressed"));const before=await readFile(compressed,"utf8");assert.equal((await readFile(compressed+".sha256","utf8")).trim(),sha256(before));await new Promise((resolve,reject)=>execFile(process.execPath,["scripts/kv-baseline-harness.mjs","compare",dense,compressed,out],{cwd:path.resolve(".")},e=>e?reject(e):resolve()));assert.equal(await readFile(compressed,"utf8"),before);await rm(dir,{recursive:true,force:true});});
