//! Per-image subject masks for training datasets (epic 2123, sc-2126).
//!
//! A subject mask is a single-channel PNG the same size as its dataset image: white (255) marks the
//! subject, black (0) the background, intermediate values a soft edge. Masks are produced by the
//! `dataset_subject_mask` job (SAM3 "person" segmentation, unioned over every detected person) or
//! uploaded by the user as a replacement, and are consumed by the masked-loss trainer (S5).
//!
//! # Storage convention (stable — S5 reads it)
//!
//! * Mask file: `<dataset root>/masks/<content hash>.png`, where `<content hash>` is the image's
//!   [`TrainingDatasetItem::content_hash`] (SHA-256 of the stored image bytes, lowercase hex).
//!   [`subject_mask_relative_path`] builds the dataset-root-relative path and
//!   [`resolve_subject_mask_path`] resolves an item's mask to an absolute path.
//! * Index: `<dataset root>/dataset.sceneworks.subject-masks.json`, a content-hash-keyed map of
//!   [`SubjectMaskRecord`] (source, empty flag, dimensions, timestamp).
//!
//! Keying on the content hash — like the CLIP and face sidecars — rather than the item id or file
//! name is deliberate: the dataset editor rematerializes `images/` on every save and the batch
//! rename changes ids and stems, but neither changes pixels, so a mask survives both untouched. A
//! re-pointed / cropped / replaced image has a new hash, so its stale mask simply stops matching
//! (and is pruned on the next mask write) instead of silently masking different pixels.

use std::collections::BTreeMap;
use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};

use image::{DynamicImage, GrayImage, ImageFormat, Limits};
use serde::{Deserialize, Serialize};

use crate::project_store::{ProjectStoreError, ProjectStoreResult};
use crate::store_util::{atomic_write, relative_string, write_json};
use crate::time::utc_now;
use crate::training::{TrainingDataset, TrainingDatasetItem};
use crate::training_store::{
    dataset_item_path, dataset_root, ensure_dataset_project, TrainingDatasetStore,
};

/// Dataset-root-relative directory holding the mask PNGs.
pub const SUBJECT_MASK_DIR: &str = "masks";
/// The content-hash-keyed mask index beside the dataset manifest.
pub const SUBJECT_MASK_INDEX_NAME: &str = "dataset.sceneworks.subject-masks.json";
/// Largest accepted encoded mask (upload or worker write). The web dataset editor enforces the same
/// limit before uploading (`SUBJECT_MASK_MAX_UPLOAD_BYTES` in `apps/web/src/training/subjectMasks.js`).
pub const SUBJECT_MASK_MAX_UPLOAD_BYTES: u64 = 32 * 1024 * 1024;
/// Largest accepted mask edge in pixels (bounds the decode allocation of a tiny-but-huge PNG).
pub const SUBJECT_MASK_MAX_EDGE: u32 = 16_384;
/// A mask whose aspect ratio differs from its image's by more than this fraction is refused rather
/// than stretched; within it the mask is resized deterministically to the image's dimensions.
pub const SUBJECT_MASK_ASPECT_TOLERANCE: f64 = 0.01;
/// The multipart field a replacement mask is uploaded under — named in field-level errors.
pub const SUBJECT_MASK_UPLOAD_FIELD: &str = "file";

const SUBJECT_MASK_INDEX_SCHEMA_VERSION: u32 = 1;

/// Who produced a mask.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SubjectMaskSource {
    /// Generated by the `dataset_subject_mask` job (SAM3 person segmentation).
    Auto,
    /// Uploaded by the user as a replacement.
    Upload,
}

/// One stored mask, keyed in [`DatasetSubjectMasks::masks`] by the image content hash.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubjectMaskRecord {
    pub source: SubjectMaskSource,
    /// True when every pixel is 0 — e.g. SAM3 detected no person. The editor flags these.
    pub empty: bool,
    pub width: u32,
    pub height: u32,
    pub updated_at: String,
}

/// The on-disk mask index.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DatasetSubjectMasks {
    #[serde(default)]
    pub schema_version: u32,
    #[serde(default)]
    pub masks: BTreeMap<String, SubjectMaskRecord>,
}

/// One encoded mask to persist for the image whose content hash is `content_hash`.
#[derive(Debug, Clone)]
pub struct SubjectMaskWrite {
    pub content_hash: String,
    pub png: Vec<u8>,
}

/// Per-item mask status in a [`SubjectMaskReport`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubjectMaskItemStatus {
    pub item_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_hash: Option<String>,
    /// Project-relative path of the mask PNG (servable through the project files route), or `None`
    /// when the item has no mask.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mask_path: Option<String>,
    pub has_mask: bool,
    pub empty: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<SubjectMaskSource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

/// A dataset's mask coverage: `masked` of `total` items carry a mask; `empty` of those are all-black
/// (no subject detected) and `uploaded` were replaced by the user.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubjectMaskReport {
    pub dataset_id: String,
    pub total: usize,
    pub masked: usize,
    pub empty: usize,
    pub uploaded: usize,
    pub items: Vec<SubjectMaskItemStatus>,
}

/// One image the mask job must segment: its item id, absolute image path and content hash.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubjectMaskTarget {
    pub item_id: String,
    pub image_path: PathBuf,
    pub content_hash: String,
}

/// Dataset-root-relative path of the mask for an image with `content_hash`.
pub fn subject_mask_relative_path(content_hash: &str) -> String {
    format!("{SUBJECT_MASK_DIR}/{content_hash}.png")
}

/// Absolute path of `item`'s subject mask under `dataset_root`, or `None` when the item has no
/// content hash or no mask file exists for it. The masked-loss trainer (S5) resolves each training
/// item's mask through this.
pub fn resolve_subject_mask_path(
    dataset_root: &Path,
    item: &TrainingDatasetItem,
) -> Option<PathBuf> {
    let hash = item.content_hash.as_deref()?;
    if !is_content_hash(hash) {
        return None;
    }
    let path = dataset_root.join(subject_mask_relative_path(hash));
    path.is_file().then_some(path)
}

fn is_content_hash(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn field_invalid(code: &'static str, detail: impl Into<String>) -> ProjectStoreError {
    ProjectStoreError::FieldInvalid {
        field: SUBJECT_MASK_UPLOAD_FIELD,
        code,
        detail: detail.into(),
    }
}

/// Decode `bytes` as a mask for an image of `target` dimensions and return the single-channel mask
/// at exactly those dimensions plus whether it is empty (all zero).
///
/// PNG, JPEG and WebP are accepted. Colour masks are reduced to luma; an alpha channel multiplies
/// in (a transparent pixel is background), so a mask painted on a transparent layer reads as drawn.
/// A mask with the image's aspect ratio (within [`SUBJECT_MASK_ASPECT_TOLERANCE`]) but a different
/// size is resized with a triangle filter — deterministic, so the same upload always yields the
/// same stored bytes. Every rejection is a [`ProjectStoreError::FieldInvalid`] on the upload field.
pub fn normalize_subject_mask(
    bytes: &[u8],
    target: (u32, u32),
) -> ProjectStoreResult<(GrayImage, bool)> {
    if bytes.len() as u64 > SUBJECT_MASK_MAX_UPLOAD_BYTES {
        return Err(field_invalid(
            "subject_mask_too_large",
            format!(
                "Subject mask is {} bytes; the limit is {} MiB.",
                bytes.len(),
                SUBJECT_MASK_MAX_UPLOAD_BYTES / (1024 * 1024)
            ),
        ));
    }
    let format = match image::guess_format(bytes) {
        Ok(format @ (ImageFormat::Png | ImageFormat::Jpeg | ImageFormat::WebP)) => format,
        _ => {
            return Err(field_invalid(
                "subject_mask_unsupported_type",
                "Subject mask must be a PNG, JPEG, or WebP image.",
            ))
        }
    };
    let mut reader = image::ImageReader::with_format(Cursor::new(bytes), format);
    let mut limits = Limits::default();
    limits.max_image_width = Some(SUBJECT_MASK_MAX_EDGE);
    limits.max_image_height = Some(SUBJECT_MASK_MAX_EDGE);
    reader.limits(limits);
    let decoded = reader.decode().map_err(|error| {
        field_invalid(
            "subject_mask_undecodable",
            format!("Subject mask could not be decoded: {error}"),
        )
    })?;
    let gray = mask_luma(&decoded);
    let (target_w, target_h) = target;
    if target_w == 0 || target_h == 0 {
        return Err(ProjectStoreError::BadRequest(
            "Training dataset image has no dimensions".to_owned(),
        ));
    }
    let gray = if gray.dimensions() == target {
        gray
    } else {
        let (w, h) = gray.dimensions();
        let mask_aspect = f64::from(w) / f64::from(h.max(1));
        let image_aspect = f64::from(target_w) / f64::from(target_h);
        if w == 0
            || h == 0
            || (mask_aspect / image_aspect - 1.0).abs() > SUBJECT_MASK_ASPECT_TOLERANCE
        {
            return Err(field_invalid(
                "subject_mask_dimensions_mismatch",
                format!(
                    "Subject mask is {w}x{h} but the image is {target_w}x{target_h}; upload a mask \
                     with the same size or aspect ratio."
                ),
            ));
        }
        image::imageops::resize(
            &gray,
            target_w,
            target_h,
            image::imageops::FilterType::Triangle,
        )
    };
    let empty = gray.as_raw().iter().all(|&value| value == 0);
    Ok((gray, empty))
}

fn mask_luma(decoded: &DynamicImage) -> GrayImage {
    if !decoded.color().has_alpha() {
        return decoded.to_luma8();
    }
    let luma_alpha = decoded.to_luma_alpha8();
    let (w, h) = luma_alpha.dimensions();
    let pixels = luma_alpha
        .pixels()
        .map(|pixel| {
            let [luma, alpha] = pixel.0;
            ((u16::from(luma) * u16::from(alpha) + 127) / 255) as u8
        })
        .collect();
    GrayImage::from_raw(w, h, pixels).expect("one byte per pixel")
}

fn encode_png(mask: &GrayImage) -> ProjectStoreResult<Vec<u8>> {
    let mut out = Vec::new();
    mask.write_to(&mut Cursor::new(&mut out), ImageFormat::Png)
        .map_err(|error| ProjectStoreError::Io(std::io::Error::other(error.to_string())))?;
    Ok(out)
}

fn index_path(project_path: &Path, dataset_id: &str) -> PathBuf {
    dataset_root(project_path, dataset_id).join(SUBJECT_MASK_INDEX_NAME)
}

fn read_index(project_path: &Path, dataset_id: &str) -> ProjectStoreResult<DatasetSubjectMasks> {
    match fs::read(index_path(project_path, dataset_id)) {
        Ok(bytes) => Ok(serde_json::from_slice(&bytes)?),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            Ok(DatasetSubjectMasks::default())
        }
        Err(error) => Err(ProjectStoreError::Io(error)),
    }
}

/// The image dimensions a mask must match: the item's recorded size, else its file header.
fn item_dimensions(
    project_path: &Path,
    dataset: &TrainingDataset,
    item: &TrainingDatasetItem,
) -> ProjectStoreResult<(u32, u32)> {
    if let (Some(w), Some(h)) = (item.width, item.height) {
        return Ok((w, h));
    }
    let path = dataset_item_path(project_path, dataset, item)?;
    crate::media_convert::image_dimensions(&path).ok_or_else(|| {
        ProjectStoreError::BadRequest(format!(
            "Training dataset image {} has unreadable dimensions",
            item.id
        ))
    })
}

impl TrainingDatasetStore {
    /// Fill a missing `content_hash` on every item (legacy items predate sc-6531), persisting the
    /// backfill so masks — which are keyed by it — resolve through [`resolve_subject_mask_path`].
    /// Metadata-only: no version bump.
    fn backfill_content_hashes(&self, dataset: &mut TrainingDataset) -> ProjectStoreResult<()> {
        let mut changed = false;
        for index in 0..dataset.items.len() {
            if dataset.items[index].content_hash.is_some() {
                continue;
            }
            let path = dataset_item_path(self.project_path(), dataset, &dataset.items[index])?;
            dataset.items[index].content_hash =
                Some(crate::media_convert::file_content_hash(&path)?);
            changed = true;
        }
        if changed {
            self.save_dataset(dataset)?;
        }
        Ok(())
    }

    /// The images the mask job segments — every item, or only `item_ids` when given (an unknown id is
    /// refused). Backfills missing content hashes first.
    pub fn subject_mask_targets(
        &self,
        project_id: &str,
        dataset_id: &str,
        item_ids: Option<&[String]>,
    ) -> ProjectStoreResult<Vec<SubjectMaskTarget>> {
        let mut dataset = self.read_dataset_by_id(dataset_id)?;
        ensure_dataset_project(project_id, &dataset)?;
        if let Some(ids) = item_ids {
            if let Some(unknown) = ids
                .iter()
                .find(|id| !dataset.items.iter().any(|item| &item.id == *id))
            {
                return Err(ProjectStoreError::FieldInvalid {
                    field: "itemIds",
                    code: "subject_mask_unknown_item",
                    detail: format!("Training dataset item {unknown} not found"),
                });
            }
        }
        self.backfill_content_hashes(&mut dataset)?;
        dataset
            .items
            .iter()
            .filter(|item| item_ids.is_none_or(|ids| ids.iter().any(|id| id == &item.id)))
            .map(|item| {
                Ok(SubjectMaskTarget {
                    item_id: item.id.clone(),
                    image_path: dataset_item_path(self.project_path(), &dataset, item)?,
                    content_hash: item
                        .content_hash
                        .clone()
                        .expect("content hashes were backfilled above"),
                })
            })
            .collect()
    }

    /// Persist generated (or uploaded) masks. Each write's content hash must belong to a current
    /// dataset item; its PNG is normalized against that item's dimensions
    /// ([`normalize_subject_mask`]) and stored at [`subject_mask_relative_path`]. Masks of images no
    /// longer in the dataset are pruned. Metadata-only: no version bump. Returns the coverage report.
    pub fn write_subject_masks(
        &self,
        project_id: &str,
        dataset_id: &str,
        writes: Vec<SubjectMaskWrite>,
        source: SubjectMaskSource,
    ) -> ProjectStoreResult<SubjectMaskReport> {
        let mut dataset = self.read_dataset_by_id(dataset_id)?;
        ensure_dataset_project(project_id, &dataset)?;
        self.backfill_content_hashes(&mut dataset)?;
        let root = dataset_root(self.project_path(), dataset_id);
        let mut index = read_index(self.project_path(), dataset_id)?;
        let now = utc_now();
        for write in writes {
            if !is_content_hash(&write.content_hash) {
                return Err(ProjectStoreError::BadRequest(
                    "Subject mask contentHash must be a SHA-256 hex digest".to_owned(),
                ));
            }
            let item = dataset
                .items
                .iter()
                .find(|item| item.content_hash.as_deref() == Some(write.content_hash.as_str()))
                .ok_or_else(|| {
                    ProjectStoreError::NotFound(format!(
                        "No training dataset image has content hash {}",
                        write.content_hash
                    ))
                })?;
            let dims = item_dimensions(self.project_path(), &dataset, item)?;
            let (mask, empty) = normalize_subject_mask(&write.png, dims)?;
            atomic_write(
                &root.join(subject_mask_relative_path(&write.content_hash)),
                &encode_png(&mask)?,
            )?;
            index.masks.insert(
                write.content_hash,
                SubjectMaskRecord {
                    source,
                    empty,
                    width: mask.width(),
                    height: mask.height(),
                    updated_at: now.clone(),
                },
            );
        }
        // Prune masks whose image left the dataset (removed, re-pointed, cropped).
        let live: Vec<&str> = dataset
            .items
            .iter()
            .filter_map(|item| item.content_hash.as_deref())
            .collect();
        let stale: Vec<String> = index
            .masks
            .keys()
            .filter(|hash| !live.contains(&hash.as_str()))
            .cloned()
            .collect();
        for hash in stale {
            index.masks.remove(&hash);
            match fs::remove_file(root.join(subject_mask_relative_path(&hash))) {
                Ok(()) => {}
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
                Err(error) => return Err(ProjectStoreError::Io(error)),
            }
        }
        index.schema_version = SUBJECT_MASK_INDEX_SCHEMA_VERSION;
        write_json(&index_path(self.project_path(), dataset_id), &index)?;
        self.build_subject_mask_report(&dataset, &index)
    }

    /// Install a user-uploaded replacement mask for one item, read from `source_path` (the API's
    /// streamed temp file). Validation failures are field-level errors on the upload field.
    pub fn upload_subject_mask(
        &self,
        project_id: &str,
        dataset_id: &str,
        item_id: &str,
        source_path: &Path,
    ) -> ProjectStoreResult<SubjectMaskReport> {
        let mut dataset = self.read_dataset_by_id(dataset_id)?;
        ensure_dataset_project(project_id, &dataset)?;
        if !dataset.items.iter().any(|item| item.id == item_id) {
            return Err(ProjectStoreError::NotFound(
                "Training dataset item not found".to_owned(),
            ));
        }
        let size = fs::metadata(source_path)?.len();
        if size > SUBJECT_MASK_MAX_UPLOAD_BYTES {
            return Err(field_invalid(
                "subject_mask_too_large",
                format!(
                    "Subject mask is {size} bytes; the limit is {} MiB.",
                    SUBJECT_MASK_MAX_UPLOAD_BYTES / (1024 * 1024)
                ),
            ));
        }
        self.backfill_content_hashes(&mut dataset)?;
        let content_hash = dataset
            .items
            .iter()
            .find(|item| item.id == item_id)
            .and_then(|item| item.content_hash.clone())
            .expect("content hashes were backfilled above");
        let png = fs::read(source_path)?;
        self.write_subject_masks(
            project_id,
            dataset_id,
            vec![SubjectMaskWrite { content_hash, png }],
            SubjectMaskSource::Upload,
        )
    }

    /// The dataset's current mask coverage.
    pub fn subject_mask_report(
        &self,
        project_id: &str,
        dataset_id: &str,
    ) -> ProjectStoreResult<SubjectMaskReport> {
        let dataset = self.read_dataset_by_id(dataset_id)?;
        ensure_dataset_project(project_id, &dataset)?;
        let index = read_index(self.project_path(), dataset_id)?;
        self.build_subject_mask_report(&dataset, &index)
    }

    fn build_subject_mask_report(
        &self,
        dataset: &TrainingDataset,
        index: &DatasetSubjectMasks,
    ) -> ProjectStoreResult<SubjectMaskReport> {
        let root = dataset_root(self.project_path(), &dataset.id);
        let mut items = Vec::with_capacity(dataset.items.len());
        for item in &dataset.items {
            // A record only counts when its file is really there (and vice versa an orphan file with
            // no record is not a mask): coverage must describe what the trainer will read.
            let record = item.content_hash.as_deref().and_then(|hash| {
                let record = index.masks.get(hash)?;
                resolve_subject_mask_path(&root, item).map(|path| (record, path))
            });
            items.push(match record {
                Some((record, path)) => SubjectMaskItemStatus {
                    item_id: item.id.clone(),
                    content_hash: item.content_hash.clone(),
                    mask_path: Some(relative_string(self.project_path(), &path)?),
                    has_mask: true,
                    empty: record.empty,
                    source: Some(record.source),
                    updated_at: Some(record.updated_at.clone()),
                },
                None => SubjectMaskItemStatus {
                    item_id: item.id.clone(),
                    content_hash: item.content_hash.clone(),
                    mask_path: None,
                    has_mask: false,
                    empty: false,
                    source: None,
                    updated_at: None,
                },
            });
        }
        Ok(SubjectMaskReport {
            dataset_id: dataset.id.clone(),
            total: items.len(),
            masked: items.iter().filter(|item| item.has_mask).count(),
            empty: items
                .iter()
                .filter(|item| item.has_mask && item.empty)
                .count(),
            uploaded: items
                .iter()
                .filter(|item| item.source == Some(SubjectMaskSource::Upload))
                .count(),
            items,
        })
    }
}

#[cfg(test)]
mod tests;
